cruding:
  entity_class_alias_map:
    domain/declaration: App\Domaining\Entity\DomainDeclaration
  form_type_map:
    App\Domaining\Entity\DomainDeclaration: App\Domaining\Form\DomainDeclarationType

  route_guard:
    require_runtime_lock: false
